# This workflow adds the "not stale" label to all PRs opened by copybara-service[bot] so that these are skipped from the stale workflow 
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions-ecosystem/action-add-labels
name: Add label to copybara-service PRs

on:
  pull_request:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-ecosystem/action-add-labels@v1
        if: github.actor == 'copybara-service[bot]'
        with:
          labels: not stale
          debug-only: true
